//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub paper_id: i64,
    #[sea_orm(column_type = "Text")]
    pub file_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::papers::Entity",
        from = "Column::PaperId",
        to = "super::papers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Papers,
}

impl Related<super::papers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Papers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
