//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "keywords")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub word: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::paper_keywords::Entity")]
    PaperKeywords,
}

impl Related<super::paper_keywords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperKeywords.def()
    }
}

impl Related<super::papers::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_keywords::Relation::Papers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_keywords::Relation::Keywords.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
