//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub color: String,
    pub document_count: Option<i64>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::paper_labels::Entity")]
    PaperLabels,
}

impl Related<super::paper_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperLabels.def()
    }
}

impl Related<super::papers::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_labels::Relation::Papers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_labels::Relation::Label.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
