//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod attachments;
pub mod authors;
pub mod category;
pub mod keywords;
pub mod label;
pub mod paper_authors;
pub mod paper_keywords;
pub mod paper_labels;
pub mod papers;
