//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "papers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#abstract: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub doi: Option<String>,
    pub publication_year: Option<i64>,
    #[sea_orm(ignore, column_type = "custom(\"DATE\")", select_as = "text", nullable)]
    pub publication_date: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub journal_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub conference_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub volume: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issue: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pages: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    pub citation_count: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub read_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(has_many = "super::paper_authors::Entity")]
    PaperAuthors,
    #[sea_orm(has_many = "super::paper_category::Entity")]
    PaperCategory,
    #[sea_orm(has_many = "super::paper_keywords::Entity")]
    PaperKeywords,
    #[sea_orm(has_many = "super::paper_labels::Entity")]
    PaperLabels,
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::paper_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperAuthors.def()
    }
}

impl Related<super::paper_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperCategory.def()
    }
}

impl Related<super::paper_keywords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperKeywords.def()
    }
}

impl Related<super::paper_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperLabels.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_authors::Relation::Papers.def().rev())
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_category::Relation::Category.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_category::Relation::Papers.def().rev())
    }
}

impl Related<super::keywords::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_keywords::Relation::Keywords.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_keywords::Relation::Papers.def().rev())
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::paper_labels::Relation::Label.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::paper_labels::Relation::Papers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
