//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "paper_keywords")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub paper_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub keyword_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keywords::Entity",
        from = "Column::KeywordId",
        to = "super::keywords::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Keywords,
    #[sea_orm(
        belongs_to = "super::papers::Entity",
        from = "Column::PaperId",
        to = "super::papers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Papers,
}

impl Related<super::keywords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Keywords.def()
    }
}

impl Related<super::papers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Papers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
