//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "paper_authors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub paper_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub author_id: i64,
    pub author_order: i64,
    pub is_corresponding: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub correspondence_email: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::authors::Entity",
        from = "Column::AuthorId",
        to = "super::authors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Authors,
    #[sea_orm(
        belongs_to = "super::papers::Entity",
        from = "Column::PaperId",
        to = "super::papers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Papers,
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Authors.def()
    }
}

impl Related<super::papers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Papers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
