//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::attachments::Entity as Attachments;
pub use super::authors::Entity as Authors;
pub use super::category::Entity as Category;
pub use super::keywords::Entity as Keywords;
pub use super::label::Entity as Label;
pub use super::paper_authors::Entity as PaperAuthors;
pub use super::paper_category::Entity as PaperCategory;
pub use super::paper_keywords::Entity as PaperKeywords;
pub use super::paper_labels::Entity as PaperLabels;
pub use super::papers::Entity as Papers;
